# Generated by Django 4.0.5 on 2022-06-30 14:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeid', models.CharField(blank=True, max_length=10, null=True, verbose_name='Employee ID Number')),
                ('department', models.CharField(max_length=125)),
                ('role', models.CharField(max_length=125)),
                ('employeetype', models.CharField(max_length=15, null=True, verbose_name='Employee Type')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('employee_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeCheckOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_out_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('attendance_status', models.CharField(max_length=125, null=True, verbose_name='attendance_status')),
                ('attendance_type', models.CharField(max_length=125, verbose_name='attendance_type')),
                ('employee_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.employeeprofile')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeCheckIN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('employee_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
